ssh key test

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -86,22 +86,21 @@ jobs:
       - name: Create .ssh directory and add EC2 host key
         # run은 명령을 실행하는데 사용한다.
         # ssh 연결 시 호스트 키 확인 절차를 자동화하고 보안을 강화한다.
+        #          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/authorized_keys
         run: |
           mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
-      #          mkdir -p ~/.ssh
-      #          touch ~/.ssh/known_hosts
-      #          touch ~/.ssh/known_hosts_backup
-      #          if ! ssh-keygen -F ${{ secrets.EC2_HOST }} > /dev/null; then
-      #            HOST_KEY=$(ssh-keyscan -H ${{ secrets.EC2_HOST }} | awk '{print $2}')
-      #            EXPECTED_KEY="${{ secrets.EC2_HOST_KEY }}"
-      #            if [ "$HOST_KEY" == "$EXPECTED_KEY" ]; then
-      #              ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
-      #            else
-      #              echo "Host key verification failed! Proceeding with caution."
-      #              ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts_backup
-      #            fi
-      #          fi
+          touch ~/.ssh/authorized_keys
+          touch ~/.ssh/authorized_keys_backup
+          if ! ssh-keygen -F ${{ secrets.EC2_HOST }} > /dev/null; then
+            HOST_KEY=$(ssh-keyscan -H ${{ secrets.EC2_HOST }} | awk '{print $2}')
+            EXPECTED_KEY="${{ secrets.EC2_HOST_KEY }}"
+            if [ "$HOST_KEY" == "$EXPECTED_KEY" ]; then
+              ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/authorized_keys
+            else
+              echo "Host key verification failed! Proceeding with caution."
+              ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/authorized_keys_backup
+            fi
+            fi
 
       # ec2 접속을 위해 깃허브에서 설정한 ssh key (pem key)를 생성하고 권한을 부여
       - name: Create private key file
